# main menu
[[main]]
weight = 1
name = "Events"
hasChildren = true

  [[main]]
  parent = "Events"
  name = "HeroCTF v7"
  url = "events/heroctf-v7"
  weight = 6

  parent = "Events"
  name = "HeroCTF v6"
  url = "events/heroctf-v6"
  weight = 7

  [[main]]
  parent = "Events"
  name = "HeroCTF v5"
  url = "events/heroctf-v5"
  weight = 8

  [[main]]
  parent = "Events"
  name = "HeroCTF v4"
  url = "events/heroctf-v4"
  weight = 9

  [[main]]
  parent = "Events"
  name = "HeroCTF v3"
  url = "events/heroctf-v3"
  weight = 10

[[main]]
name = "About"
url = "about/"
weight = 2
  
[[main]]
name = "Contact"
url = "contact/"
weight = 3

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Contact"
url = "contact/"
weight = 2

[[footer]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 3
